apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewogICAgICAgICJhdXRocyI6IHsKICAgICAgICAgICAgICAgICJnaGNyLmlvIjogewogICAgICAgICAgICAgICAgICAgICJhdXRoIiA6ICJiVzl5YTJGeVlXZG9PbWRvY0Y5S2NrTjJTekpoTUdOdVdVWjZXVzVuVHpodlRYZHlVVTFvVEV0WlRXVXhNMkl6Um1nPSIKICAgICAgICAgICAgICAgIH0KICAgICAgICB9Cn0K
type: kubernetes.io/dockerconfigjson
